services:
  postgres:
    image: docker.io/postgres:15
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-p", "5432", "-U", "food_rating_dev", "-d", "food_rating_dev" ]
    environment:
      POSTGRES_USER: food_rating_dev
      POSTGRES_PASSWORD: food_rating_dev
      POSTGRES_DB: food_rating_dev
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5499:5432"
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: food_rating_dev
      MINIO_ROOT_PASSWORD: food_rating_dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-volume:/data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  db-volume:
  minio-volume:
